Description of nt_normcol
Home > NoiseTools > nt_normcol.m
nt_normcol
PURPOSE
[y,norm]=nt_normcol(x,w) - normalize each column so its weighted msq is 1
SYNOPSIS
function [y,norm]=nt_normcol(x,w)
DESCRIPTION
 [y,norm]=nt_normcol(x,w) - normalize each column so its weighted msq is 1
   y: normalized data
   norm: vector of norms
   x: data to normalize
   w: weight
 If x is 3D, pages are concatenated vertically before calculating the
 norm. If x is 4D, apply normcol to each book.
 Weight should be either a column vector, or a matrix (2D or 3D) of same
 size as data.
 See nt_normrow.
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_normcol [y,norm]=nt_normcol(x,w) - normalize each column so its weighted msq is 1
nt_unfold y=nt_fold(x) - unfold 3D to 2D
nt_vecmult y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
This function is called by:
nt_bias_cluster [c0,c1,A,todss,pwr0,pwr1]=nt_bias_cluster(x,dsr,flags) - cluster covariance
nt_cca_aad [D,E,R]=nt_cca_match_aad(xA,xB,y,ssize) - calculate metrics for match-mismatch task
nt_cca_crossvalidate [AA,BB,RR,iBest]=nt_cca_crossvalidate(xx,yy,shifts,ncomp,A0,B0) - CCA with cross-validation
nt_cca_crossvalidate2 [A,B,RR]=nt_cca_crossvalidate2(xx,yy,shifts) - CCA with cross-validation
nt_cca_crossvalidate_3 [AA,BB,RR,iBest]=nt_cca_crossvalidate(xx,yy,shifts,ncomp,A0,B0) - CCA with cross-validation
nt_cca_mm [D,E,R]=nt_cca_mm(x,y,ssize,ldaflag,nccs) - calculate metrics for match-mismatch task
nt_cca_mm_old [D,E,R]=nt_cca_mm(x,y,ssize) - calculate metrics for match-mismatch task
nt_cluster_jd [IDX,todss,SCORE,COVS]=nt_cluster_jd(x,dsr,smooth,flags,init,verbose) - cluster with joint diagonalization
nt_dss1 [todss,pwr0,pwr1]=nt_dss1(x,w,keep1,keep2) - evoked-biased DSS denoising
nt_inpaint function y=nt_inpaint(x,w) - weighted interpolation based on correlation structure
nt_narrowband_scan A=nt_narrowband_scan(x,freqs,sr,Q,plotflag) - scan for narrowband components using DSS
nt_normcol [y,norm]=nt_normcol(x,w) - normalize each column so its weighted msq is 1
nt_normpagecol y=nt_normpagecol(x,w) - normalize each column of each page so its weighted msq is 1
nt_outliers [w,y]=nt_outliers(x,w,thresh,niter) - detect outliers based on weighted correlation structure
nt_sns1 y=nt_sns1(x,nneigbors,skip,w,threshold) - sensor noise suppression
nt_spect_plot2 nt_spect_plot2 - plot power spectrum
nt_split_jd [idx,score_vector,todss]=nt_split_dss(x,thresh,depth) - segmentation based on joint diagonalization
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsr_nodemean [y,idx,w]=nt_tsr_nodemean(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
SOURCE CODE
function [y,norm]=nt_normcol(x,w)
% [y,norm]=nt_normcol(x,w) - normalize each column so its weighted msq is 1
%
%   y: normalized data
%   norm: vector of norms
%
%   x: data to normalize
%   w: weight
%
% If x is 3D, pages are concatenated vertically before calculating the
% norm. If x is 4D, apply normcol to each book.
%
% Weight should be either a column vector, or a matrix (2D or 3D) of same
% size as data.
%
% See nt_normrow.
%
% NoiseTools
if nargin<2; w=[]; end
if isempty(x); error('empty x'); end
if iscell(x)
    if nargin>1; error('weights not supported for cell array'); end
    disp('warning: normalizing each cell individually');
    y={};
    for iCell=1:numel(x);
        y{iCell}=nt_normcol(x{iCell});
    end
    return
end
if ndims(x)==4;
    if nargin>1; error('weights not supported for 4D data'); end
    [m,n,o,p]=size(x);
    y=zeros(size(x));
    N=zeros(1,n);
    for k=1:p
        [y(:,:,:,k),NN]=nt_normcol(x(:,:,:,k));
        N=N+NN.^2;
    end
    return
end
if ndims(x)==3;
    % 3D: unfold, apply normcol on 2D, fold
    [m,n,o]=size(x);
    x=nt_unfold(x);
    if isempty(w);
        % no weight
        [y,NN]=nt_normcol(x);
        N=NN.^2;
        y=nt_fold(y,m);
    else
        % weight
        if size(w,1)~=m; error('weight matrix should have same nrows as data'); end
        if ndims(w)==2 && size(w,2)==1;
            w=repmat(w,[1,m,o]);
        end
        if size(w)~=size(w); error('weight should have same size as data'); end
        w=nt_unfold(w);
        [y,NN]=nt_normcol(x,w);
        N=NN.^2;
        y=nt_fold(y,m);
    end
else
    % 2D
    [m,n]=size(x);
    if isempty(w)
        % no weight
        %N=sqrt(sum(x.^2)/m);
        %y=vecmult(x,1./N);
        N=(sum(x.^2)/m);
        NN=N.^-0.5;
        NN(find(N==0))=0;
        y=nt_vecmult(x,NN);
    else
        % weight
        if size(w,1)~=size(x,1); error('weight matrix should have same ncols as data'); end
        if ndims(w)==2 && size(w,2)==1;
            w=repmat(w,1,n);
        end
        if size(w)~=size(w); error('weight should have same size as data'); end
        if size(w,2)==1; w=repmat(w,1,n);end
        %N=sqrt(sum((x.^2).*w)./sum(w));
        %y=vecmult(x,1./N);
        N=(sum((x.^2).*w)./sum(w));
        NN=N.^-0.5;
        NN(find(N==0))=0;
        y=nt_vecmult(x, NN);
    end
end
norm=N.^0.5;